# Generated by Django 3.0 on 2019-12-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_auto_20191204_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Date',
            field=models.DateField(),
        ),
    ]
