# Generated by Django 3.0 on 2019-12-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_auto_20191204_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='Other_activities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='Primary_fur_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='Specific_location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
