# Generated by Django 3.0 on 2019-12-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0005_auto_20191204_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Other_activities',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='Primary_fur_color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
