# Generated by Django 3.0 on 2019-12-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0006_auto_20191204_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.AlterField(
            model_name='show',
            name='Unique_squirrel_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
