# Generated by Django 3.0 on 2019-12-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0007_auto_20191205_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Date',
            field=models.DateField(),
        ),
    ]
